### ISSUE TITLE
Where does the random() function come from?

### ISSUE THREAD

**Issue by colejd** [G3Kappa/pictomaze#1]
Hello! I'm trying to convert some of your code to JS. I'm experienced with Python, but I've never seen the `random()` invocations that you're making, and I can't seem to find any definition for them in the rest of the code. What am I missing?

Thanks!

**Comment by colejd** [comment]
Looking further, I see that you probably didn't intend this repo to be a full-functioning program, but rather just the essential bits for supplementing your article. I'll treat `random` as a function that gives a number between 0 and the argument. Sorry for the trouble!

**Comment by giovinazzo-kevin** [comment]
Hey! Sorry for not replying earlier. Yeah, random is just a "good enough" random function that returns numbers in the 0-1 range. Math.random() in JS should do the trick.

E: Either way, the random() function comes from Processing. The repo itself is a fully functioning program to be run in Processing in Python mode (ergo .pyde).

https://processing.org/reference/random_.html
